### ISSUE TITLE
Does it support Not Filter?

### ISSUE THREAD

**Issue by starchou** [mattbaird/elastigo#150]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-not-filter.html

**Comment by mikeyoon** [comment]
Linking https://github.com/mattbaird/elastigo/pull/177 for reference. This will include setting Not filter when merged.

**Comment by mikeyoon** [comment]
#238 is merged now, so this should be available.

**Comment by starchou** [comment]
:+1:
