### ISSUE TITLE
what's the recommended git hash for v1 ?

### ISSUE THREAD

**Issue by Dieterbe** [mattbaird/elastigo#153]
assuming v2 is still less stable/good than v1 (is it?), which git hash should we use for v1?
the readme says to use godep, which is fine, but it's not clear what's the recommended git hash for v1.
i see there's a git tag for v1.0, but looking at the git history shows that some fixes got merged after that tag, however the readme also says that v2.0 development started 2014-07-09 but it's not clear at which point that work broke master.
it seems that a separate v1 branch would be useful for this case.
thanks.

**Comment by mattbaird** [comment]
I believe the hash is 0c98885a2b2575c99882263dfc4bf6aae9079a63

Yes, we probably should have created a branch, will do next large breaking change.
