### ISSUE TITLE
_cat/shards and _cat/indices support

### ISSUE THREAD

**Issue by weberr13** [mattbaird/elastigo#192]
I have home grown support for _cat/shards and _cat/indices and I was wondering if this is something of interest here and how you want the data provided through the API.  Is there a plan in this direction already or is it something I should throw in a PR and see what you think?

**Comment by mattbaird** [comment]
Hi @weberr13 PR's are accepted regularly. I am pretty busy these days with new startup.
Net new PR's are fast to merge (tests please)
breaking changes take me longer because I still have to figure out the least invasive was to do this.

thanks!

**Comment by weberr13** [comment]
Thanks, I put a pull request up with my stuff.  tested in goconvey.

**Comment by weberr13** [comment]
Hey @mattbaird I've noticed a growing backlog of requests on this project.  Our company is using it actively and we have two golang developers (myself included) who are willing to take on maintenence of this project.  If you are warm to this idea please contact me here.  The other dev would be https://github.com/vrecan

**Comment by mattbaird** [comment]
Hi @weberr13 shoot me an email mattbaird at gmail and we'll talk about how it could work.
