### ISSUE TITLE
Is the latest version compatible with elasticsearch 1.5 on ubuntu14.04?

### ISSUE THREAD

**Issue by k1xme** [mattbaird/elastigo#199]
Sorry for bothering, but I can't find any document up-to-date that mentions the supporting OSes and ES versions.

**Comment by epelc** [comment]
@k1xme I'm currently running it with 1.5 on ubuntu 14.04 on compute engine.

I'm not an elasticsearch expert yet but basic queries and filters are working fine and have been for a few weeks.

**Comment by weberr13** [comment]
I run 1.5.2 on centos, I don't see any reason it wouldn't work on ubuntu 14.04.
