### ISSUE TITLE
Update in Bulk API

### ISSUE THREAD

**Issue by dmichael** [mattbaird/elastigo#29]
Hi @araddon 

Today I was interested in adding an update to the bulk API. The entire API implicitly assumes that you are only using the "index" op. So let's chat - what would be a good way to add the Update? Perhaps something like this?

``` go
func (b *BulkIndexor) Update(index string, _type string, id, ttl string, date *time.Time, data interface{}) error {
    by, err := UpdateBulkBytes(index, _type, id, ttl, date, data)
    if err != nil {
        u.Error(err)
        return err
    }
    b.bulkChannel <- by
    return nil
}
```

**Comment by Dieterbe** [comment]
this has been merged as of https://github.com/mattbaird/elastigo/pull/31 and can be closed.
